import React from 'react';
import { ScanRecord, ClinicianUser } from '../types';
import { DR_SEVERITY_LEVELS } from '../lib/constants';
import { X, Printer, Download, CheckCircle2, Shield, Eye } from 'lucide-react';

interface ReportModalProps {
  scan: ScanRecord | null;
  currentUser: ClinicianUser;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ scan, currentUser, onClose }) => {
  if (!scan) return null;

  const severity = DR_SEVERITY_LEVELS[scan.drSeverityLevel];

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadText = () => {
    const reportText = `===================================================================
RETINALENS CLINICAL DIABETIC RETINOPATHY SCREENING REPORT
Hospital / Clinic Node: ${currentUser.clinicId || 'Rural Health Ophthalmic Node'}
Clinician: ${currentUser.displayName} (${currentUser.email})
===================================================================

PATIENT INFORMATION:
Patient ID: ${scan.patientId}
Examined Eye: ${scan.eyeSide === 'OD' ? 'Right Eye (OD)' : 'Left Eye (OS)'}
Pupil Status: ${scan.pupilDilationStatus}
Acquisition Timestamp: ${new Date(scan.uploadedAt).toLocaleString()}

DIAGNOSTIC SEVERITY CLASSIFICATION:
Grade: ${severity.name} (ICDR Level ${scan.drSeverityLevel})
Confidence Index: ${scan.confidenceScore.toFixed(1)}%
Severity Description: ${severity.description}
Recommended Clinical Action: ${severity.clinicalAction}

PATHOLOGICAL FINDINGS:
${
  scan.findings.length > 0
    ? scan.findings.map((f, i) => `${i + 1}. ${f.label} (${f.severity}): ${f.description}`).join('\n')
    : 'No observable microaneurysms, hemorrhages, or exudates.'
}

EXPLAINABLE AI ATTRIBUTION:
Attribution Summary: ${scan.explainabilityNotes}
Inference Pipeline: ${scan.modelSource}
Telemetry Saliency Sector: ${scan.telemetry.primaryAttributionSector}

===================================================================
Report Generated by RetinaLens Edge AI Pipeline
HIPAA Compliant • End-to-End Encrypted Node • DICOM 3.0 Standard
===================================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `RetinaLens_Report_${scan.patientId}_${scan.eyeSide}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md overflow-y-auto">
      <div className="relative w-full max-w-2xl bg-[#060d23] border border-[#00f0ff]/40 rounded-2xl shadow-[0_0_40px_rgba(0,240,255,0.2)] overflow-hidden my-8">
        {/* Top cyan glow highlight */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-transparent via-[#00f0ff] to-transparent" />

        {/* Modal Header */}
        <div className="flex items-center justify-between p-5 border-b border-[#3b494b]/30 bg-[#0b1228]">
          <div className="flex items-center gap-2.5">
            <Eye className="w-5 h-5 text-[#00f0ff]" />
            <h3 className="text-base font-bold text-[#dbfcff] font-heading">
              Clinical Telemetry Screening Report
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-[#181f35] text-[#b9cacb] hover:text-white transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Report Content Body (Print friendly) */}
        <div id="printable-report" className="p-6 space-y-6 text-[#dbe1ff]">
          {/* Clinic & Patient Header */}
          <div className="flex flex-col sm:flex-row justify-between gap-4 pb-4 border-b border-[#3b494b]/30">
            <div>
              <span className="text-xs text-[#7bd0ff] font-semibold block uppercase tracking-wider">
                Health Node & Clinician
              </span>
              <span className="text-sm font-bold text-[#dbfcff] block">
                {currentUser.clinicId || 'Rural Outreach Ophthalmic Node'}
              </span>
              <span className="text-xs text-[#b9cacb]">
                Clinician: {currentUser.displayName} • {currentUser.email}
              </span>
            </div>

            <div className="text-left sm:text-right">
              <span className="text-xs text-[#7bd0ff] font-semibold block uppercase tracking-wider">
                Patient Telemetry
              </span>
              <span className="text-sm font-bold text-[#dbfcff] font-mono block">
                {scan.patientId} ({scan.eyeSide})
              </span>
              <span className="text-xs text-[#b9cacb]">
                {new Date(scan.uploadedAt).toLocaleDateString(undefined, {
                  year: 'numeric',
                  month: 'short',
                  day: 'numeric',
                })}
              </span>
            </div>
          </div>

          {/* Diagnostic Grade Banner */}
          <div
            style={{
              backgroundColor: severity.badgeBg,
              borderColor: severity.badgeBorder,
              color: severity.badgeText,
            }}
            className="p-4 rounded-xl border flex flex-col gap-1"
          >
            <div className="flex items-center justify-between">
              <span className="text-xs uppercase font-bold tracking-wider">
                Final Automated Classification
              </span>
              <span className="text-xs font-mono font-bold">
                Confidence: {scan.confidenceScore.toFixed(1)}%
              </span>
            </div>
            <span className="text-lg font-extrabold">{severity.name}</span>
            <p className="text-xs opacity-90 mt-1">{severity.description}</p>
            <div className="mt-2 pt-2 border-t border-current/20 text-xs font-semibold">
              Clinical Recommendation: {severity.clinicalAction}
            </div>
          </div>

          {/* Fundus Preview + Findings */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="sm:col-span-1 rounded-xl overflow-hidden border border-[#3b494b]/50 bg-black aspect-square">
              <img src={scan.imageUrl} alt="Fundus Scan" className="w-full h-full object-cover" />
            </div>

            <div className="sm:col-span-2 space-y-2">
              <span className="text-xs font-bold text-[#dbfcff] block uppercase tracking-wider">
                Identified Pathologies ({scan.findings.length})
              </span>
              {scan.findings.length > 0 ? (
                <div className="space-y-1.5">
                  {scan.findings.map((f) => (
                    <div
                      key={f.id}
                      className="p-2 rounded-lg bg-[#141b31] border border-[#3b494b]/30 text-xs"
                    >
                      <div className="flex items-center justify-between">
                        <strong className="text-[#00f0ff]">{f.label}</strong>
                        <span className="text-[10px] uppercase text-[#7bd0ff] font-semibold">
                          {f.severity}
                        </span>
                      </div>
                      <p className="text-[11px] text-[#b9cacb] mt-0.5">{f.description}</p>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-[#10b981]">No lesions or retinal hemorrhages observed.</p>
              )}
            </div>
          </div>

          {/* Explainability Summary */}
          <div className="p-3.5 rounded-xl bg-[#141b31]/70 border border-[#3b494b]/30 text-xs space-y-1">
            <span className="font-semibold text-[#7bd0ff] uppercase tracking-wider block text-[10px]">
              Explainable AI Saliency Summary
            </span>
            <p className="text-[#b9cacb] leading-relaxed">{scan.explainabilityNotes}</p>
          </div>
        </div>

        {/* Modal Actions */}
        <div className="flex items-center justify-end gap-3 p-4 border-t border-[#3b494b]/30 bg-[#0b1228]">
          <button
            onClick={handleDownloadText}
            className="px-4 py-2 rounded-xl bg-[#181f35] hover:bg-[#222940] border border-[#3b494b]/50 text-[#dbfcff] text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Save Report (.txt)</span>
          </button>

          <button
            onClick={handlePrint}
            className="px-4 py-2 rounded-xl bg-gradient-to-r from-[#00f0ff] to-[#00a6e0] text-[#002022] font-bold text-xs flex items-center gap-1.5 shadow-[0_0_15px_rgba(0,240,255,0.4)] hover:brightness-110 active:scale-95 transition-all cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Clinical Summary</span>
          </button>
        </div>
      </div>
    </div>
  );
};
